In [1]:
#GroupBy :- splitting data into groups based on some criteria, applying a function to each group independently,
#and then combining the results into a data structure.

#Split: The data is divided into groups based on the values in one or more specified keys (columns).

#Apply: A function (e.g., aggregation, transformation, or filtration) is executed on each individual group.

#Combine: The results of the 'Apply' step are merged back together into a single pandas object (usually a Series or DataFrame).



#Common Aggregation Functions
#FunctionDescription
# .sum()Compute sum of group values
# .mean()Compute mean of group values
# .std()Compute standard deviation of group values
# .min()Compute minimum of group values
# .max()Compute maximum of group values
# .count()Compute count of non-null values
# .size()Compute size of the group (including NaN)
#     .first()Return first non-null entry in each group
#     .last()Return last non-null entry in each group


#Basic Syntax and Aggregation
#grouped_data = df.groupby(column_name)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/nishantgiri/Desktop/DataFile/data.csv")
df

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

      Fname     Lname  Age          City Occupation  Salary
0    Sophia       Lee   22      New York      Pilot   76121
1     James    Taylor   58      Columbus     Doctor   30977
2      Jack    Garcia   56        Dallas  Scientist   39683
3     Isaac    Martin   30        Austin  Architect   75545
4      Noah    Taylor   30      New York  Architect   60659
..      ...       ...  ...           ...        ...     ...
105   Grace    Miller   50       Seattle     Doctor   40175
106  Hannah  Anderson   34  Philadelphia      Pilot   61504
107   Frank     Brown   47  Philadelphia    Teacher   98922
108   Lucas       Lee   27   Los Angeles     Artist   95970
109  Oliver   Johnson   38  Indianapolis  Scientist   76965

[110 rows x 6 columns]

In [3]:
#What is the average salary of each occupation?
df.groupby('Occupation')['Salary'].mean()

Occupation
Accountant    48208.500000
Architect     62824.812500
Artist        73524.285714
Doctor        55929.000000
Engineer      64173.071429
Journalist    50886.250000
Lawyer        69686.928571
Pilot         73311.272727
Scientist     68697.666667
Teacher       63917.875000
Name: Salary, dtype: float64

In [6]:
#How many people work in each occupation?
df.groupby('Occupation')['Fname'].count()

Occupation
Accountant     6
Architect     16
Artist         7
Doctor        12
Engineer      14
Journalist     4
Lawyer        14
Pilot         11
Scientist     18
Teacher        8
Name: Fname, dtype: int64

In [ ]:
# avg age in each occupation.
#total salary in each occupation.
#max Salary in each occupation.
#count of people in each city.
#avg salary in each city.
#min salary in each occupation.
#total salary in each city.
#count of people in each age group.

In [15]:
#count of people in each age group.
age = df.Age.unique()
print(sorted(age))

[np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59)]

In [20]:
group1 = df["Age"][df["Age"].isin(range(20,30))]
group2 = df["Age"][df["Age"].isin(range(31,40))]
group3 = df["Age"][df["Age"].isin(range(41,50))]
group4 = df["Age"][df["Age"].isin(range(51,60))]

In [30]:
print(len(group1))

26

In [34]:
# 19. Which occupation has the highest total salary?
# - Group by `Occupation`, sum `Salary`, then find the occupation with the highest total.
df.groupby('Occupation')['Salary'].sum()

Occupation
Accountant     289251
Architect     1005197
Artist         514670
Doctor         671148
Engineer       898423
Journalist     203545
Lawyer         975617
Pilot          806424
Scientist     1236558
Teacher        511343
Name: Salary, dtype: int64

In [38]:
# 20. Which city has the highest average salary?
# - Group by `City`, calculate the mean of `Salary`, then find the highest.
df.groupby('City')["Salary"].mean()

City
Austin          62699.800000
Charlotte       63007.000000
Chicago         63871.125000
Columbus        60512.600000
Dallas          61327.666667
Houston         66851.142857
Indianapolis    68431.833333
Los Angeles     68082.333333
New York        62701.428571
Philadelphia    80325.666667
Phoenix         59439.375000
San Antonio     62991.750000
San Diego       46086.500000
San Jose        67323.750000
Seattle         72874.500000
Name: Salary, dtype: float64

In [40]:
# 21. What is the distribution of occupations across cities?
# - Group by `City` and `Occupation`, use `.size()` to count.
df.groupby(['City', 'Occupation']).size().rename('Count')

City      Occupation
Austin    Architect     2
          Artist        1
          Doctor        1
          Journalist    1
          Lawyer        2
                       ..
San Jose  Teacher       1
Seattle   Doctor        2
          Engineer      1
          Lawyer        2
          Scientist     1
Name: Count, Length: 83, dtype: int64

In [45]:
# 22. What is the average salary of people aged 30 and above in each occupation?
# - Filter by `Age >= 30`, group by `Occupation`, calculate the mean of `Salary`.
df[df['Age'] >= 30].groupby('Occupation')['Salary'].mean()

Occupation
Accountant    48208.500000
Architect     67641.181818
Artist        64390.200000
Doctor        51947.363636
Engineer      64744.888889
Journalist    50984.000000
Lawyer        70285.111111
Pilot         70778.500000
Scientist     69373.937500
Teacher       66624.857143
Name: Salary, dtype: float64

In [48]:
# 23. Which age group has the highest salary in each occupation?
# - Group by `Occupation` and `Age`, find the maximum salary.
df.groupby(['Occupation','Age'])['Salary'].max()

Occupation  Age
Accountant  40     45547
            44     30695
            52     81429
            58     60977
Architect   26     41725
                   ...
Teacher     41     73547
            45     36944
            47     98922
            55     79157
            58     54319
Name: Salary, Length: 93, dtype: int64

In [49]:
# 24. What is the distribution of salaries in each occupation?
# - Group by `Occupation`, use `.describe()` to get a summary (mean, median, etc.).
df.groupby("Occupation").describe()

             Age                                                       Salary  \
           count       mean        std   min    25%   50%    75%   max  count
Occupation
Accountant   6.0  50.666667   7.339391  40.0  46.00  52.0  56.50  58.0    6.0
Architect   16.0  39.125000  11.563592  26.0  28.00  36.5  50.00  57.0   16.0
Artist       7.0  42.142857  13.533028  26.0  30.50  42.0  53.50  59.0    7.0
Doctor      12.0  44.666667  10.421423  24.0  40.00  47.5  50.25  58.0   12.0
Engineer    14.0  42.500000  13.084048  25.0  28.25  45.5  54.00  56.0   14.0
Journalist   4.0  39.000000  17.813852  23.0  24.50  37.0  51.50  59.0    4.0
Lawyer      14.0  38.357143  12.493735  22.0  28.25  37.5  45.50  59.0   14.0
Pilot       11.0  36.636364  10.327369  22.0  29.00  34.0  45.50  52.0   11.0
Scientist   18.0  42.833333   9.972020  24.0  35.75  42.0  51.75  56.0   18.0
Teacher      8.0  42.500000  11.032420  27.0  35.25  43.0  49.00  58.0    8.0

                                                                              \
                    mean           std      min       25%      50%       75%
Occupation
Accountant  48208.500000  19709.306408  30695.0  33408.75  42317.0  57119.50
Architect   62824.812500  16561.191234  38532.0  47010.25  61365.5  76027.50
Artist      73524.285714  27488.817992  32816.0  51023.50  92603.0  95227.50
Doctor      55929.000000  21794.789965  30977.0  37982.50  56580.0  68564.25
Engineer    64173.071429  15856.486940  39138.0  52494.25  64914.5  67904.00
Journalist  50886.250000  10231.148758  38469.0  47252.25  50788.5  54422.50
Lawyer      69686.928571  20545.939368  39575.0  54305.00  64457.5  89876.75
Pilot       73311.272727  18415.107461  33813.0  68143.50  76291.0  83012.50
Scientist   68697.666667  17090.110715  38910.0  60558.50  69600.0  79363.25
Teacher     63917.875000  20299.695975  36944.0  51140.00  62303.5  74949.50


                max
Occupation
Accountant  81429.0
Architect   88413.0
Artist      96749.0
Doctor      99727.0
Engineer    97152.0
Journalist  63499.0
Lawyer      97182.0
Pilot       99057.0
Scientist   95844.0
Teacher     98922.0

In [55]:
# 25. What is the age distribution in each city?
# - Group by `City`, calculate the mean and standard deviation of `Age`.
df.groupby("City")["Age"].agg(['mean','std'])

                   mean        std
City
Austin        40.100000  13.576532
Charlotte     42.250000   9.377024
Chicago       40.750000  12.612352
Columbus      43.400000  13.390295
Dallas        45.777778  12.163242
Houston       35.571429  13.010984
Indianapolis  46.833333  11.651895
Los Angeles   41.000000  10.380270
New York      34.714286  12.711075
Philadelphia  42.777778   8.105211
Phoenix       43.750000  12.139075
San Antonio   36.750000   9.145647
San Diego     50.333333   5.125102
San Jose      41.500000  15.066519
Seattle       38.333333  14.787382

In [57]:
# 26. What is the total salary of people aged below 40 in each occupation?
# - Filter by `Age < 40`, group by `Occupation`, calculate the sum of `Salary`.
df[df["Age"] <40].groupby("Occupation")["Salary"].sum()

Occupation
Architect     556648
Artist        285322
Doctor        234445
Engineer      379899
Journalist    101577
Lawyer        586923
Pilot         536159
Scientist     634171
Teacher       168454
Name: Salary, dtype: int64

In [59]:
# 27. Which city has the youngest average population?
# - Group by `City`, calculate the mean of `Age`, and find the minimum.
df.groupby("City")["Age"].agg(['mean','min'])

                   mean  min
City
Austin        40.100000   22
Charlotte     42.250000   24
Chicago       40.750000   25
Columbus      43.400000   27
Dallas        45.777778   25
Houston       35.571429   26
Indianapolis  46.833333   28
Los Angeles   41.000000   27
New York      34.714286   22
Philadelphia  42.777778   34
Phoenix       43.750000   25
San Antonio   36.750000   26
San Diego     50.333333   44
San Jose      41.500000   27
Seattle       38.333333   24

In [60]:
# 28. Which occupation has the oldest average age?
# - Group by `Occupation`, calculate the mean of `Age`, and find the maximum.
df.groupby("Occupation")["Age"].agg(['mean','max'])

                 mean  max
Occupation
Accountant  50.666667   58
Architect   39.125000   57
Artist      42.142857   59
Doctor      44.666667   58
Engineer    42.500000   56
Journalist  39.000000   59
Lawyer      38.357143   59
Pilot       36.636364   52
Scientist   42.833333   56
Teacher     42.500000   58

In [67]:
# 29. What is the total number of people in each city-occupation combination?
# - Group by `City` and `Occupation`, count occurrences.
df.groupby(["City","Occupation"]).count()

                     Fname  Lname  Age  Salary
City     Occupation
Austin   Architect       2      2    2       2
         Artist          1      1    1       1
         Doctor          1      1    1       1
         Journalist      1      1    1       1
         Lawyer          2      2    2       2
...                    ...    ...  ...     ...
San Jose Teacher         1      1    1       1
Seattle  Doctor          2      2    2       2
         Engineer        1      1    1       1
         Lawyer          2      2    2       2
         Scientist       1      1    1       1

[83 rows x 4 columns]

In [74]:
# 30. What is the average salary in each occupation, sorted by salary?
# - Group by `Occupation`, calculate the mean of `Salary`, and sort the result.
df.groupby("Occupation")["Salary"].mean().sort_values(ascending=False)

Occupation
Artist        73524.285714
Pilot         73311.272727
Lawyer        69686.928571
Scientist     68697.666667
Engineer      64173.071429
Teacher       63917.875000
Architect     62824.812500
Doctor        55929.000000
Journalist    50886.250000
Accountant    48208.500000
Name: Salary, dtype: float64

In [75]:
# 31. Which occupation has the highest salary variance?
# - Group by `Occupation`, calculate the variance of `Salary`.
df.groupby("Occupation")["Salary"].var()

Occupation
Accountant    3.884568e+08
Architect     2.742731e+08
Artist        7.556351e+08
Doctor        4.750129e+08
Engineer      2.514282e+08
Journalist    1.046764e+08
Lawyer        4.221356e+08
Pilot         3.391162e+08
Scientist     2.920719e+08
Teacher       4.120777e+08
Name: Salary, dtype: float64

In [76]:
# 32. Which city has the most diverse set of occupations?
# - Group by `City`, use `.nunique()` on `Occupation`.
df.groupby("City")["Occupation"].nunique()

City
Austin          7
Charlotte       5
Chicago         6
Columbus        4
Dallas          7
Houston         7
Indianapolis    6
Los Angeles     5
New York        4
Philadelphia    7
Phoenix         6
San Antonio     7
San Diego       5
San Jose        3
Seattle         4
Name: Occupation, dtype: int64

In [78]:
# 33. What is the median salary in each city?
# - Group by `City`, calculate the median of `Salary`.
df.groupby("City")["Salary"].median()

City
Austin          60921.0
Charlotte       65770.5
Chicago         63513.5
Columbus        62072.0
Dallas          60224.0
Houston         70288.0
Indianapolis    70232.0
Los Angeles     70887.0
New York        60659.0
Philadelphia    89150.0
Phoenix         54404.0
San Antonio     65771.5
San Diego       42143.5
San Jose        70364.5
Seattle         74156.0
Name: Salary, dtype: float64

In [85]:
# 34. What is the average salary for people named 'Sophia'?
# - Filter by `Fname == 'Sophia'`, calculate the mean of `Salary`.
df[df["Fname"] == 'Sophia']["Salary"].mean()

np.float64(80903.6)

In [100]:
# 35. What is the proportion of people in each occupation in the dataset?
# - Group by `Occupation`, count occurrences, and normalize to get proportions.
# df.groupby("Occupation")["Occupation"].count()/len(df)
# df.groupby("Occupation").size()/len(df)
df["Occupation"].value_counts(normalize=True)

Occupation
Scientist     0.163636
Architect     0.145455
Engineer      0.127273
Lawyer        0.127273
Doctor        0.109091
Pilot         0.100000
Teacher       0.072727
Artist        0.063636
Accountant    0.054545
Journalist    0.036364
Name: proportion, dtype: float64

In [101]:
# 36. What is the highest salary for each combination of city and occupation?
# - Group by `City` and `Occupation`, calculate the maximum of `Salary`.
df.groupby(["City","Occupation"])["Salary"].max()

City      Occupation
Austin    Architect     75545
          Artist        48063
          Doctor        71811
          Journalist    50180
          Lawyer        54054
                        ...
San Jose  Teacher       79157
Seattle   Doctor        99727
          Engineer      51851
          Lawyer        97182
          Scientist     61562
Name: Salary, Length: 83, dtype: int64

In [102]:
# 37. How many people aged over 50 work in each city?
# - Filter by `Age > 50`, group by `City`, count occurrences.
df[df["Age"] > 50].groupby("City").count()

              Fname  Lname  Age  Occupation  Salary
City
Austin            3      3    3           3       3
Charlotte         2      2    2           2       2
Chicago           3      3    3           3       3
Columbus          2      2    2           2       2
Dallas            5      5    5           5       5
Houston           2      2    2           2       2
Indianapolis      3      3    3           3       3
Los Angeles       2      2    2           2       2
New York          1      1    1           1       1
Philadelphia      2      2    2           2       2
Phoenix           3      3    3           3       3
San Antonio       1      1    1           1       1
San Diego         2      2    2           2       2
San Jose          2      2    2           2       2
Seattle           1      1    1           1       1

In [103]:
# 38. Which age group earns the most in each city?
# - Group by `City` and `Age`, calculate the mean of `Salary`.
df.groupby(["City","Age"])["Salary"].mean()

City     Age
Austin   22     48333.0
         23     50180.0
         30     75545.0
         33     83172.0
         37     71811.0
                 ...
Seattle  24     80644.5
         29     51851.0
         44     86750.0
         50     40175.0
         59     97182.0
Name: Salary, Length: 99, dtype: float64

In [109]:
# 39. What is the salary range (max - min) in each occupation?
# - Group by `Occupation`, calculate the salary range (`max - min`)
df.groupby("Occupation")["Salary"].agg(lambda x:x.max()-x.min())

Occupation
Accountant    50734
Architect     49881
Artist        63933
Doctor        68750
Engineer      58014
Journalist    25030
Lawyer        57607
Pilot         65244
Scientist     56934
Teacher       61978
Name: Salary, dtype: int64