In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"./sales_data.csv")
df

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,03-02-2023,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,21-04-2023,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,21-09-2023,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,24-08-2023,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,24-03-2023,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,15-04-2023,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,07-09-2023,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,27-04-2023,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,20-12-2023,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,16-08-2023,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [4]:
df.pivot_table(index="Region", values="Sales_Amount",aggfunc="sum")

        Sales_Amount
Region
East      1259792.93
North     1369612.51
South     1154250.86
West      1235608.93

In [5]:
df.pivot_table(index="Product_Category", values="Sales_Amount", columns="Region",aggfunc="sum")

Region                 East      North      South       West
Product_Category
Clothing          356670.40  372977.22  269517.74  314309.00
Electronics       303101.42  342666.29  293663.96  304067.97
Food              325864.87  258985.65  301187.51  315735.51
Furniture         274156.24  394983.35  289881.65  301496.45

In [6]:
df.pivot_table(index="Sales_Rep", values="Quantity_Sold", columns=["Region","Sales_Channel"],aggfunc="sum")

Region          East         North         South          West
Sales_Channel Online Retail Online Retail Online Retail Online Retail
Sales_Rep
Alice            566    752    727    494    636    576    653    428
Bob              754    563    493    650    510    462    752    793
Charlie          279    715    674    510    391    471    813    364
David            682    772    725    905    816    683    620    839
Eve              572    701    794    733    610    653    535    689

In [7]:
df.pivot_table(index="Sales_Rep", values="Sales_Amount", columns=["Region","Sales_Channel"],aggfunc=["count","sum","mean"])

               count                                                   \
Region          East         North         South          West
Sales_Channel Online Retail Online Retail Online Retail Online Retail
Sales_Rep
Alice             19     33     26     22     23     22     28     19
Bob               35     25     19     25     27     23     24     30
Charlie           12     25     31     24     14     18     31     14
David             29     30     25     31     28     28     24     27
Eve               26     29     29     35     20     23     18     29

                     sum             ...                               mean  \
Region              East             ...       West                    East
Sales_Channel     Online     Retail  ...     Online     Retail       Online
Sales_Rep                            ...
Alice          100546.35  160243.12  ...  125893.45   89797.09  5291.913158
Bob            174097.17  135778.94  ...  115458.06  170991.22  4974.204857
Charlie         46959.31  118213.63  ...  162716.89   76991.96  3913.275833
David          141496.17  143117.34  ...  121402.61  141764.98  4879.178276
Eve            112123.27  127217.63  ...   84413.81  146178.86  4312.433462

                                                                   \
Region                            North                     South
Sales_Channel       Retail       Online       Retail       Online
Sales_Rep
Alice          4855.852121  5540.968462  4799.183636  5818.746522
Bob            5431.157600  5637.398421  5054.169600  4301.356296
Charlie        4728.545200  4742.354194  6365.667917  6501.864286
David          4770.578000  5777.324000  4455.037742  6052.372143
Eve            4386.814828  4845.228621  4676.016286  4006.653500


Region                             West
Sales_Channel       Retail       Online       Retail
Sales_Rep
Alice          4799.244091  4496.194643  4726.162632
Bob            5872.339565  4810.752500  5699.707333
Charlie        3617.476667  5248.931935  5499.425714
David          5069.663214  5058.442083  5250.554815
Eve            5041.093478  4689.656111  5040.650345

[5 rows x 24 columns]

In [8]:
df.pivot_table(index="Payment_Method", values="Sales_Amount", columns="Customer_Type",aggfunc=["count","sum","mean","max"])

               count                 sum                    mean               \
Customer_Type    New Returning       New  Returning          New    Returning
Payment_Method
Bank Transfer    181       161  889778.5  827584.67  4915.903315  5140.277453
Cash             160       153  779810.5  764528.04  4873.815625  4996.915294
Credit Card      163       182  836669.3  920894.22  5132.940491  5059.858352

                    max
Customer_Type       New Returning
Payment_Method
Bank Transfer   9775.35   9972.66
Cash            9976.52   9989.04
Credit Card     9961.96   9948.71

In [9]:
df.pivot_table(index="Payment_Method", values="Unit_Price", columns="Region_and_Sales_Rep",aggfunc=["count","sum","mean","max"])

                          count                                            \
Region_and_Sales_Rep East-Alice East-Bob East-Charlie East-David East-Eve
Payment_Method
Bank Transfer                18       24           12         22       14
Cash                         16       19           10         19       16
Credit Card                  18       17           15         18       25

                                                                      \
Region_and_Sales_Rep North-Alice North-Bob North-Charlie North-David
Payment_Method
Bank Transfer                 16        13            18          14
Cash                          14        16            19          18
Credit Card                   18        15            18          24

                                ...         max                          \
Region_and_Sales_Rep North-Eve  ... South-Alice South-Bob South-Charlie
Payment_Method                  ...
Bank Transfer               22  ...     5044.74   5040.22       5253.07
Cash                        17  ...     5017.58   4720.27       3384.50
Credit Card                 25  ...     4624.10   5043.36       5079.65

                                                                             \
Region_and_Sales_Rep South-David South-Eve West-Alice West-Bob West-Charlie
Payment_Method
Bank Transfer            5026.19   4973.38    5245.86  5191.02      4985.75
Cash                     4785.66   4879.15    4743.03  4612.49      5184.64
Credit Card              4879.72   5129.19    5309.32  5088.06      4995.55


Region_and_Sales_Rep West-David West-Eve
Payment_Method
Bank Transfer           5011.43  4537.94
Cash                    5119.91  4675.90
Credit Card             5166.72  5088.00

[3 rows x 80 columns]

In [10]:
df.pivot_table(index='Sales_Channel',values='Unit_Price',columns='Payment_Method')

Payment_Method  Bank Transfer         Cash  Credit Card
Sales_Channel
Online            2886.064368  2740.228742  2729.864663
Retail            2646.338452  2644.958272  2716.782088